---
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    toc: true
params:
  child: yes
---

> "If I take it up I must understand every detail," said he. "Take time to consider. The smallest point may be the most essential." --- Sherlock Holmes The Adventure of the Red Circle

For a couple of [decades](https://twitter.com/f2harrell/status/1449014869798395905) we have been loyal users of the [Hmisc](https://cran.r-project.org/web/packages/Hmisc/index.html) package in general and the [describe](https://rdrr.io/cran/Hmisc/man/describe.html) function in particular as a way to explore data before any analyses. As it is often the case in the R ecosystem, there are numerous ways to accomplish this task (see summarizing data blogs [here](https://dabblingwithdata.wordpress.com/2018/01/02/my-favourite-r-package-for-summarising-data) and [here](https://dabblingwithdata.wordpress.com/2018/02/26/r-packages-for-summarising-data-part-2/) for a dated but yet extensive review). Our love affair with `Hmisc::describe` originated due to its concise look pre [rmarkdown](https://rmarkdown.rstudio.com/) days (Sweave/Latex/PDF) and its linking with SAS formatted data sets (containing labels, formats, special missing). Indeed, in the clinical research industry, SAS formatted data sets (SAS transport `.xpt` or native `.sas7bdat` files) remain widely used, while the R language continues to grow in [popularity](https://rinpharma.com/). [Dr. Frank Harrell](https://www.fharrell.com/), who developed the Hmisc package, has been from our perspective a luminary as he lays out the possibilities embedded in the R language especially in the clinical research environment.

For some time now we wanted to modernize the aforementioned `describe` function to provide a modern and interactive interface after years of the static (HTML and/or PDF) report. The [`datadigest`](https://cran.r-project.org/web/packages/datadigest/index.html) package was an effort to build an interactive data explorer inspired by `Hmisc::describe`; the package leveraged `JavaScript` for interactivity, with `htmlwidget` and `Shiny` interfaces for use in R. Since the release of `datadigest`, the R community has continued to deliver increasingly powerful frameworks for interactive displays. Therefore, We took the [2021 RStudio Table Contest](https://www.rstudio.com/blog/rstudio-table-contest-2021/) as an opportunity to accomplish the goal of building an interactive interface for `describe` using tools available in R. In particular by using the power of [reactable](https://cran.r-project.org/web/packages/reactable/index.html) combined with embedded with [plotly](https://cran.r-project.org/web/packages/plotly/index.html) interactive figures within a modern [flexdashboard](https://pkgs.rstudio.com/flexdashboard/) to generate concise summaries of every variable in a data set with minimal user configuration. In other for other users to utilize such a powerful summary table we went a step further and wrapped our work into the [describer](https://github.com/agstn/describer) package.

For this challenge we selected a [CDISC](https://www.cdisc.org/) (Clinical Data Interchange Standards Consortium) [ADaM](https://www.cdisc.org/standards/foundational/adam) (Analysis Data Model) ADSL (Analysis Data Subject Level) subset dataset as an illustration. The ADSL dataset structure is one record per subject and contains variables such as subject-level population flags, planned and actual treatment variables, demographic information, randomization factors, subgrouping variables, and important dates originated from the [PHUSE CDISC Pilot replication study](https://github.com/phuse-org/phuse-scripts/tree/master/data/adam/cdisc).



<b>AUTHORS</b> <br>

---

- Agustin Calatroni
- Becca Krouse
- Stephanie Lussier
